# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160529_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
