language: python
python:
  - "3.5"
install: "pip install -r requirements.txt"

before_script: 
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
script: python hashtags/manage.py test functional_tests
