language: python

python:
  - "3.5"

dist: trusty
sudo: required
addons:
  packages:
    - unzip
    - google-chrome-stable

before_install:
    # Install Chrome driver
    - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo chmod u+x chromedriver
    - sudo mv chromedriver /usr/bin/

    # For selenium in headless linux system
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

install:
  - "pip install -r requirements.txt"

before_script:
  - python hashtags/manage.py makemigrations

script:
  - python hashtags/manage.py test -v 3 hashtags/
  - coverage run hashtags/manage.py test -v 3 hashtags/

after_success:
  - coveralls
